on:
  pull_request:
    branches: [ master ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Syntax check
        run: |
          IS_ERROR=0
          for FILE in `git diff HEAD ${{ github.base_ref }} --name-only | grep .php`; do
              if ! php -l $FILE; then
                  IS_ERROR=1
                  break
              fi
          done
          exit $IS_ERROR